# Generated by Django 4.1.3 on 2022-11-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('symptomOne', models.TextField()),
                ('symptomTwo', models.TextField()),
                ('consultedOn', models.DateField()),
            ],
        ),
    ]
