# Generated by Django 4.1.3 on 2022-11-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('patients', models.ManyToManyField(related_name='doctors', to='app1.patient')),
            ],
        ),
    ]
