# Generated by Django 4.1.3 on 2022-11-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptomOne',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptomTwo',
        ),
    ]
