# Generated by Django 4.1.3 on 2022-11-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_patient_symptomone_remove_patient_symptomtwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consultedWith',
            field=models.CharField(default='', max_length=50),
        ),
    ]
