# Generated by Django 4.1.3 on 2022-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patient_consultedwith'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='nithishbanda2021@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
