# Generated by Django 4.1.3 on 2022-11-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_doctor_email_alter_doctor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specializations',
        ),
    ]
