# Generated by Django 4.1.3 on 2022-11-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_specialization_doctor_specializations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medicationName', models.CharField(max_length=50)),
                ('rxNormCode', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('additionalInstructions', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='snippets',
            field=models.ManyToManyField(related_name='doctors', to='app1.snippet'),
        ),
    ]
